apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngateway
  namespace: { { projectId } }
  labels:
    component: ngateway
    sys: project
    project: { { projectId } }
    provider: nscale
spec:
  replicas: 1
  selector:
    matchLabels:
      component: ngateway
      project: { { projectId } }
      provider: nscale
  template:
    metadata:
      labels:
        component: ngateway
        sys: project
        project: { { projectId } }
        provider: nscale
    spec:
      containers:
        - name: ngateway
          image: img.nscale.io/nscale/ngateway
          imagePullPolicy: Never
          ports:
            - name: http-filter
              protocol: TCP
              containerPort: 5000
